### ISSUE TITLE
I think cepl.sdl2-ttf:quit shadows cepl:quit

### ISSUE THREAD

**Issue by podiki** [cbaggers/cepl.sdl2-ttf#1]
I'm not quite sure about this, but seems like `cepl.sdl2-ttf:quit` shadows `cepl:quit`. For instance, try `(ql:quickload :cepl.sdl2)`. Then `(cepl:quit)` will produce an error (haven't called `(cepl:repl)` yet). However, if you then quickload this package, `(cepl:quit)` will just return `nil`. I don't know if I'm understanding this correctly, but is that because `cepl.sdl2-ttf` `:use`s `#:cepl` and then `:export`s `:quit`?

**Comment by podiki** [comment]
Yup, renaming `cepl.sdl2-ttf:quit` to something else fixes this. I'm guessing there's another way with declaring shadowing or not so that both `cepl:quit` and `cepl.sdl2-ttf:quit` work as is.

**Comment by cbaggers** [comment]
Ah good point. I'm wondering if people will prefer to `:use` the package or just use qualified symbols. I thinking we should rename `init` to `init-cepl-sdl2-ttf` & `quit` to `quit-cepl-sdl2-ttf` that way people can `:use` the package and the only downside is those 2 functions having ugly names. Given that (at most) those functions will be called once each in a program I think that is an ok balance.

What do you think?

**Comment by podiki** [comment]
I agree, better to have a unique name and avoid the confusion (`cepl:quit` not doing what I expected I thought was on my end). And those names are descriptive at least.

**Comment by podiki** [comment]
Closing, as it was fixed.
